name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install
        working-directory: build

      - name: Gerar build
        run: npm run build
        working-directory: build

      - name: Copiar arquivos para a raiz
        shell: bash
        run: |
          shopt -s extglob
          rm -rf !(build|.git|.github|README.md|.gitignore)
          cp -r build/dist/* ./

      - name: Commit e push do conteúdo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy automático via GitHub Actions" || echo "Nada para commitar"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
